version: '3'

services:
  web:
    container_name: "web"
    build:
      context: .
      dockerfile: ./Dockerfiles/web/Dockerfile
    volumes:
      - ./web:/app
      - ./db:/user_modules/db
    ports:
      - 60101:8080
    env_file:
      - ./envs/db.env
      - ./envs/discord.env
      - ./envs/github.env
      - ./envs/secret.env
    restart: always

  bot:
    container_name: "bot"
    build:
      context: .
      dockerfile: ./Dockerfiles/bot/Dockerfile
    volumes:
      - ./bot:/app
      - ./db:/user_modules/db
    env_file:
      - ./envs/db.env
      - ./envs/discord.env
      - ./envs/sentry.env
    restart: always